version: '2'

services:


### Workspace Utilities Container ###########################

    workspace:
        restart: always
        build:
            context: workspace
            args:
                - TZ=$TZ
                - PUID=1000
                - PGID=1000
                - INSTALL_MEMCACHED=true
                - INSTALL_EXIF=true
                - INSTALL_OPCACHE=true
                - INSTALL_MYSQLI=true
                - INSTALL_INTL=false
                - INSTALL_XDEBUG=false
                - INSTALL_BLACKFIRE=false
                - INSTALL_WORKSPACE_SSH=false
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_NODE=true
                - NODE_VERSION=stable
                - INSTALL_YARN=true
                - YARN_VERSION=latest
        labels:
            io.rancher.container.pull_image: always
        volumes:
            - $APPLICATION_VOLUME_PATH:/home/bitrix/www
        networks:
            - default
        tty: true


### PHP-FPM Container #######################################

    php-fpm:
        restart: always
        build:
            context: php-fpm
            args:
                - INSTALL_XDEBUG=$INSTALL_XDEBUG
                - INSTALL_SOAP=true
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_BCMATH=false
                - INSTALL_PHPREDIS=false
                - INSTALL_MEMCACHED=true
                - INSTALL_OPCACHE=true
                - INSTALL_EXIF=true
        labels:
            io.rancher.container.pull_image: always
        environment:
            - PHP_IDE_CONFIG=serverName=$VIRTUAL_HOST_MAIN
        volumes_from:
            - workspace
        expose:
            - "9000"
        links:
            - workspace
            - memcached
        extra_hosts:
            - "dockerhost:$COMPOSE_DOCKER_HOST"
        networks:
            - default


### Nginx Server Container ##################################

    nginx:
        restart: always
        build:
            context: nginx
        labels:
            io.rancher.container.pull_image: always
        volumes_from:
            - workspace
        volumes:
            - ./nginx/bx:/etc/nginx/bx
            - ./nginx/certs:/etc/nginx/ssl
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - nginx_logs:/var/log/nginx
        links:
            - php-fpm
        ports:
            - "81:80"
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST


### Memcached Container #####################################

    memcached:
        restart: always
        build: memcached
        labels:
            io.rancher.container.pull_image: always
        volumes:
            - memcached:/var/lib/memcached


### Volumes Setup ###########################################

volumes:
    memcached:
        driver: "local"
    nginx_logs:
        driver: "local"
