version: '2'

services:


### Workspace Utilities Container ###########################

  workspace:
    build:
      context: workspace
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    labels:
      io.rancher.container.pull_image: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - PHP_IDE_CONFIG=serverName=$VIRTUAL_HOST_MAIN
    volumes:
      - app:/home/bitrix
      - developer-ssh:/home/developer/.ssh
    networks:
      - default


### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: php-fpm
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    labels:
      io.rancher.container.pull_image: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes_from:
      - workspace
    links:
      - workspace
      - memcached
    environment:
      - PHP_IDE_CONFIG=serverName=$VIRTUAL_HOST_MAIN
    networks:
      - default


### Nginx Server Container ##################################

  nginx:
    build:
      context: nginx
    labels:
      io.rancher.container.pull_image: always
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes_from:
      - workspace
    volumes:
      - certs:/etc/nginx/ssl
    links:
      - php-fpm
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST


### Memcached Container #####################################

  memcached:
    build:
      context: memcached
    labels:
      io.rancher.container.pull_image: always
    restart: unless-stopped
    volumes:
      - memcached:/var/lib/memcached


### Volumes Setup ###########################################

volumes:
  app:
    driver: "local"
  certs:
    driver: "local"
  memcached:
    driver: "local"
  developer-ssh:
    driver: "local"
