#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM bezrukovp/nginx-bitrix:latest

MAINTAINER Pavel Bezrukov <bezrukov.ps@gmail.com>
